Update patch set 15
Patch Set 15:

> Patch Set 15:
> 
> Hi Lancelot,
> The ssifbridge code is already upstreamed at https://github.com/openbmc/ssifbridge so you don't need to add the code again in your repo. And the bitbake recipe is put at https://github.com/openbmc/openbmc/blob/master/meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-ssif.bb.
> You can just add below in your machine conf file:
> PREFERRED_PROVIDER_virtual/obmc-host-ipmi-hw = "phosphor-ipmi-ssif"

When I built with the upstream, there is an error below. Does it expect? I need to remove that line.
| ../git/ssifbridged.cpp: In member function 'void SsifChannel::processMessage(const boost::system::error_code&, size_t)':
| ../git/ssifbridged.cpp:134:13: error: unused variable 'len' [-Werror=unused-variable]
|   134 |     uint8_t len = rawIter[0] + 1;

Patch-set: 15
Reviewer: Gerrit User 1000920 <1000920@adbd0a64-1f21-4d83-b585-671fe73cb6e4>